auto: true
pygments: true
title: Companimation
author:
    name: Mike Fowler
    email: mike@mikefowler.me
    github: mikefowler
    twitter: michaelrfowler
baseurl: /
url: http://mikefowler.github.com/companimation
source: .
destination: ./_site
plugins: ./_plugins